// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqrnaunolwzztkjamvab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxcm5hdW5vbHd6enRramFtdmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODA0MjIsImV4cCI6MjA2MDk1NjQyMn0.Kz-pDhKSiofbtmb-Aofj0sCelQp3taTa8yAzxF4Eo6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});